Refactor/refactor toppage design
BeerShigachi/sprout pull request #8
Opened 2024-04-05 09:50 UTC by KeisukeKatagiri

### Fixes：src/Page/Wireframe/UserPageAcount/TopPage/TopPage.elm

- Hierarchy modification.
- Layout changes.
- Corrected processes that repeat multiple times, such as button creation, to call functions.

2024-04-05 10:03 UTC, BeerShigachi requested changes
まず修正をお願いしたいのは、TopPage.elmのpathです。他wireframeの下にあるサブ階層とかファイルは今は無視でいいので、TopPage.elmを意味のある階層に移動しましょう。Page/TopPage.elmにしてください。後TopPage.elmが二つ存在したりと、Wireframeの下が重複file, 重複コードや不要file, 不要コードが多いのでなのでいるもの以外全部削除してください。

2024-04-05 10:03 UTC, BeerShigachi commented on src/Color.elm
Color.elmは問題無しでおｋです。

2024-04-05 10:05 UTC, BeerShigachi requested changes
追加されたすべてのImageのファイル名がどこで何に使うためにあるのかわからないので適切なものに変更してください。

2024-04-08 06:20 UTC, KeisukeKatagiri commented
https://github.com/BeerShigachi/sprout/pull/8#pullrequestreview-1982548311
TopPage.elmのpathをPage/TopPage.elmに変更しました。
また、Page/Wireframeに関しては、

- 重複file, 重複コードや不要file, 不要コードが多い
- 一旦、削除してbranch整理する方が後々の影響が少ない。
- 画面イメージが確定していない為、現時点で削除しても問題無い。
（後々、Page/Wireframe配下のもので必要になったらGitの履歴を遡って取得する。）

Page/Wireframeフォルダごと削除しました。

2024-04-08 19:38 UTC, BeerShigachi commented
結構僕の方で難しいだろうと判断したところは僕の方でrefactorを行いました。ここにも説明を書きますが、簡単な説明は各commit messageに記載しています。

2024-04-08 20:44 UTC, BeerShigachi commented on src/Page/TopPage.elm
> +type Width = Width Float
こんな風にしてFloatじゃなくてWidth/Height型にできます。
Width/Height型の中身のFloatを値を扱いたい場合は2通って、実際に使う方法は3つあります。

```
-- pattern matching 1
func : Width -> a
func value = 
    case value of
        Width float_value -> float_value

-- pattern matching 2
func : Width -> a
func (Width float_value) = float_value

-- Unwrapping funcを作って必要なときに差し込んで使う
convertWidthToFloat : Width -> Float
convertWidthToFloat (Width float_value) = float_value

double : Float -> Float
double x = x +x 

someFunc : Width -> Float
someFunc width_ = double (convertWidthToFloat width_)

```

2024-04-10 19:22 UTC, BeerShigachi approved these changes

2024-04-10 19:23 UTC, merged